// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzqmdfpnwpcvnwfzxmew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6cW1kZnBud3Bjdm53Znp4bWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MDY4MDYsImV4cCI6MjA4ODM4MjgwNn0.CmRhFo-cI-Tn5upcugXdbtmeKHxBgBKqfOkV0GpUoOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});