// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kldxwqookfggwentuohk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsZHh3cW9va2ZnZ3dlbnR1b2hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NTIwODIsImV4cCI6MjA4OTUyODA4Mn0.qEbmXQ0AV7jfVGOm432e4C1fBaq_dSRaSHqFdZ-mDLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});